version: "3.7"
services:
    
    sqlserver:
        image: microsoft/mssql-server-linux:latest
        container_name: sqlserver
        environment:
            ACCEPT_EULA: Y
            MSSQL_SA_PASSWORD: Passw0rd
            MSSQL_PID: Express
        ports:
            - 1433:1433

    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 5672:5672
            - 15672:15672 # Web Interface

    

            