version: "3.7"
services:
    dynamodb:
        image: amazon/dynamodb-local
        container_name: dynamodb
        entrypoint: java
        command: "-jar DynamoDBLocal.jar -sharedDb"
        ports:
          - 8000:8000
networks: 
    default:
        name: dynamodb